### ISSUE TITLE
Initial configuration

### ISSUE THREAD

**Issue by MPUCEL** [rogerio-faria/qdevops#6]
Deal all, 

I would to use this tool to export/import masteritem, variables, but I'm having some initial config issues.

I've vreated qdevops new virtal proxy and created exe file as it in FAQ. When I try to run some command, even the first one in FAQ, I get the following message. Where could be the issue?

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The system cannot find the file specified.
   at QDevOpsBase.Server.QlikServer.GetServerConfig()
   at QDevOpsBase.Server.QlikServer.ExecuteCommands()
   at QDevOps.Program.Main(String[] args)

**Comment by rogerio-faria** [comment]
Hi, I added a log dll NLog.dll, and I forgot to add it to the github.
Anyway, thanks for you interest in this tool. Please, download it again and test it. 
If you still have any problems, I'll be glad to help.

**Comment by MPUCEL** [comment]
Hi, thank you for support. This helped and I'm able to create master.txt and call help command. But I got stuck in the next step when I try to get list of all apps (qdevops -u=master.txt -l). 

I get the error below, but before this I also got error related to a missing chromedriver.exe, but I've added it.
Do you have any idea where could be the reason for this?

Getting Session Ticket...
Unhandled Exception: OpenQA.Selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: headless chrome=95.0.4638.54)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.set_Url(String value)
   at QDevOpsBase.Utils.WebdriverUtils.ConnecAndLogin(IWebDriver driver, String url, String userdirectory, String user, String pass)
   at QDevOpsBase.Commands.ServerUse.GetQlikTicket(String server, String virtualproxy, String user, String userdirectory, String pass)
   at QDevOpsBase.Commands.ServerUse.Execute(JObject args, CommandsConfig conf)
   at QDevOpsBase.Server.QlikServer.ExecuteCommands()
   at QDevOps.Program.Main(String[] args)

**Comment by rogerio-faria** [comment]
Ok, for the driver, I recommed you to use the command  'qdevops -update=force' or 'qdevopsupdater driver' it will get the Chromedriver that works with your Google Chrome app. Well, seams you already solved that.

For the ERR_NAME_NOT_RESOLVED, usually is caused when qdevops machine does not have access to the host you are point at. Example: qlik server name (intranet) is 'qlik.my.com' but this name is not reachable from qdevops machine.

Anyway, qdevops should access the same URL that you access through Web brwoser.
I'll be glad to help you, in a assisted suport, like anydesk or teamviewer.

Btw, can you provide the content of master.txt ? (del password)
email me at: rogerioafaria@gmail.com
